# Generated by Django 2.2.3 on 2019-07-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhihuArticleModel',
            fields=[
                ('zhihu_id', models.BigIntegerField(primary_key=type, serialize=False)),
                ('author_id', models.CharField(max_length=100, null=True, verbose_name='作者ID')),
                ('title', models.CharField(max_length=300, null=True, verbose_name='问题标题')),
                ('content', models.TextField(null=True, verbose_name='问题内容')),
                ('image_url', models.CharField(max_length=300, null=True, verbose_name='封面图片')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('crawled_at', models.DateTimeField(auto_now=True, verbose_name='爬取得时间')),
                ('status', models.CharField(max_length=30, null=True, verbose_name='对应采集的处理方案')),
                ('mg_id', models.IntegerField(null=True)),
                ('mg_type', models.CharField(max_length=30, null=True, verbose_name='蜜果对应类型')),
            ],
            options={
                'db_table': 'crawl_zhihu_article',
                'ordering': ['zhihu_id'],
            },
        ),
    ]
