# Generated by Django 2.2.3 on 2019-07-08 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_zhihuarticlemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhihuCommentModel',
            fields=[
                ('zhihu_id', models.BigIntegerField(primary_key=type, serialize=False)),
                ('author_id', models.CharField(max_length=100, null=True, verbose_name='作者ID')),
                ('content', models.TextField(null=True, verbose_name='评论内容')),
                ('vote_count', models.IntegerField(null=True, verbose_name='点赞数量')),
                ('resource_type', models.CharField(max_length=100, null=True, verbose_name='相关内容')),
                ('resource_id', models.CharField(max_length=200, null=True, verbose_name='相关ID')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=30, null=True, verbose_name='对应采集的处理方案')),
                ('mg_id', models.IntegerField(null=True)),
                ('crawled_at', models.DateTimeField(auto_now=True, verbose_name='爬取得时间')),
            ],
            options={
                'db_table': 'crawl_zhihu_comment',
                'ordering': ['zhihu_id'],
            },
        ),
    ]
