# Generated by Django 2.2.3 on 2019-07-08 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_zhihucommentmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhihuPeopleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhihu_id', models.CharField(max_length=100, null=True, verbose_name='知乎ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('url_token', models.CharField(max_length=100, null=True)),
                ('avatar_url', models.CharField(max_length=300, null=True)),
                ('headline', models.CharField(max_length=500, null=True)),
                ('gender', models.IntegerField(null=True)),
                ('mg_id', models.IntegerField(null=True)),
                ('crawled_at', models.DateTimeField(auto_now=True, verbose_name='爬取得时间')),
            ],
            options={
                'db_table': 'crawl_zhihu_people',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='zhihuarticlemodel',
            name='zhihu_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zhihucommentmodel',
            name='zhihu_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
