# Generated by Django 2.2.3 on 2019-07-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190708_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhihuAnswerModel',
            fields=[
                ('zhihu_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('question_id', models.IntegerField(null=True, verbose_name='问题ID')),
                ('author_id', models.CharField(max_length=100, null=True, verbose_name='作者ID')),
                ('content', models.TextField(null=True, verbose_name='问题内容')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=30, null=True, verbose_name='对应采集的处理方案')),
                ('mg_id', models.IntegerField(null=True)),
                ('crawled_at', models.DateTimeField(auto_now=True, verbose_name='爬取得时间')),
            ],
            options={
                'db_table': 'crawl_zhihu_answer',
                'ordering': ['zhihu_id'],
            },
        ),
        migrations.CreateModel(
            name='ZhihuQuestionModel',
            fields=[
                ('zhihu_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True, verbose_name='问题标题')),
                ('content', models.TextField(null=True, verbose_name='问题内容')),
                ('created_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=30, null=True, verbose_name='对应采集的处理方案')),
                ('mg_id', models.IntegerField(null=True)),
                ('crawled_at', models.DateTimeField(auto_now=True, verbose_name='爬取得时间')),
            ],
            options={
                'db_table': 'crawl_zhihu_question',
                'ordering': ['zhihu_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='zhihupeoplemodel',
            options={'ordering': ['zhihu_id']},
        ),
    ]
